version: '3.8'

services:
  trinder-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trinder-api-container
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UserProfilesDb=Host=postgres-db;Port=5432;Database=TrinderUserProfilesDb;Username=postgres;Password=Legion13$%
      - ConnectionStrings__BlobStorage=DefaultEndpointsProtocol=https;AccountName=satrinderdev;AccountKey=Ep7U9hWejkHLfeQlniUvvIrWshODqrLoC3+GXPSJe/LGJ+vnV0GM08inRztBGmmg+yuWZyZ/YOCC+AStb685eg==;EndpointSuffix=core.windows.net
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres-db-container
    environment:
      - POSTGRES_DB=TrinderUserProfilesDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Legion13$%
    volumes:
      - trinder-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  trinder-db-data: