@Trinder.UserProfile.API_HostAddress = http://localhost:5160

POST {{Trinder.UserProfile.API_HostAddress}}/api/userprofile
Content-Type: application/json

{
    "userName": "user1",
    "email": "user1@testing.com",
    "bio": "Some User2 Bio"
}

###

POST {{Trinder.UserProfile.API_HostAddress}}/api/userprofile
Content-Type: application/json

{
    "userName": "deletedUser",
    "email": "deletedUser@testing.com",
    "bio": "Some User Bio that will be deleted"
}

###

PUT {{Trinder.UserProfile.API_HostAddress}}/api/userprofile
Content-Type: application/json

{
  //UpdateUserProfileInfoCommand
}

###

@id=4
GET {{Trinder.UserProfile.API_HostAddress}}/api/userprofile/{{id}}

###

DELETE {{Trinder.UserProfile.API_HostAddress}}/api/userprofile/4

###


GET {{Trinder.UserProfile.API_HostAddress}}/api/userprofile/full

###

GET {{Trinder.UserProfile.API_HostAddress}}/api/userprofile

###
